spring:
  application:
    name: HirePilotAI

  datasource:
    url: jdbc:postgresql://localhost:5432/hirepilot_ai
    username: postgres
    password: hirepilotai

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
    secret: ThisIsAHirePilotAISecretKeyForJwtGeneration2026SecureKey
    expiration: 3600000